services:
  docker-mDNS-auto:
    image: docker-mdns-auto
    build: .
#    read_only: true
    restart: on-failure:10
    privileged: true
#    security_opt:
#      - apparmor=traefik-avahi-helper
#    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:r
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket

  test1:
    build: test
    profiles: ["debug"]
    depends_on:
      - docker-mDNS-auto
    environment:
      - DUR=15
    labels:
      - mDNS.publish=test1.local

  test2:
    build: test
    profiles: ["debug"]
    depends_on:
      - docker-mDNS-auto
    environment:
      - DUR=60
    labels:
     - mDNS.publish=test2.local

  test3:
    build: test
    profiles: ["debug"]
    depends_on:
      - docker-mDNS-auto
    environment:
      - DUR=60
    labels:
     - mDNS.publish=test3.local
