services:
  docker-mdns-publisher:
    image: ghcr.io/wschildbach/docker-mdns-publisher:1.0
    build: .
    read_only: true
    # make sure the mDNS ports are reachable
    network_mode: host
    tmpfs: # provide a temp mount for the dbus socket, and for avahi
      - /run/dbus
      - /run/avahi-daemon
    restart: on-failure:10
    environment:
      - LOG_LEVEL=INFO # INFO is the default
      - PYTHONUNBUFFERED=1
    volumes:
      # map the docker socket to be able to monitor container lifecycles
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./avahi/avahi-daemon.conf:/etc/avahi/avahi-daemon.conf:ro

# the rest of this file are test/debug services that start, wait a while, then die
  test1:
    image: alpine
    command: "sleep 15"
    profiles: ["debug"]
    depends_on: [docker-mdns-publisher]
    labels: [mdns.publish=test1.mysubdomain.local]

  test2:
    image: alpine
    command: "sleep 60"
    profiles: ["debug"]
    depends_on: [docker-mdns-publisher]
    labels: [mdns.publish=test2.local]

  # the third container uses the same label as the second, to test error reporting
  test3:
    image: alpine
    command: "sleep 60"
    profiles: ["debug"]
    depends_on: [docker-mdns-publisher]
    labels: [mdns.publish=test2.local] # publish same label and expect error
