services:
  docker-mdns-publisher:
    image: docker-mdns-publisher
    build: .
    read_only: true
    restart: on-failure:10
    privileged: true
    environment:
      - LOG_LEVEL=INFO # the default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:r
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:r

# the rest of this file are test/debug services that start, wait a while, then die
  test1:
    image: alpine
    command: "sleep 15"
    profiles: ["debug"]
    depends_on: [docker-mdns-publisher]
    labels: [mdns.publish=test1.local]

  test2:
    image: alpine
    command: "sleep 60"
    profiles: ["debug"]
    depends_on: [docker-mdns-publisher]
    labels: [mdns.publish=test2.local]
