services:
  docker-mdns-publisher:
    image: ghcr.io/wschildbach/docker-mdns-publisher:0.10
    build: .
    read_only: true
    ports:
      - '5353:5353/udp' # make sure the mDNS port is reachable
    tmpfs: # provide a temp mount for the dbus socket, and for avahi
      - /tmp
      - /run/dbus
      - /run/avahi-daemon
    restart: on-failure:10
    environment:
      - LOG_LEVEL=DEBUG # INFO is the default
      - PYTHONUNBUFFERED=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./avahi/avahi-daemon.conf:/etc/avahi/avahi-daemon.conf:ro
#    networks:
#      - test

# the rest of this file are test/debug services that start, wait a while, then die
  test1:
    image: alpine
    command: "sleep 15"
    profiles: ["debug"]
    depends_on: [docker-mdns-publisher]
    labels: [mdns.publish=test1.local]
    networks:
      - test

  test2:
    image: alpine
    command: "sleep 60"
    profiles: ["debug"]
    depends_on: [docker-mdns-publisher]
    labels: [mdns.publish=test2.local]

  test3:
    image: alpine
    command: "sleep 60"
    profiles: ["debug"]
    depends_on: [docker-mdns-publisher]
    labels: [mdns.publish=test2.local] # publish same label and expect error

networks:
  test: {}
